/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Autor;
import model.Libro;

/**
 *
 * @author Carlos
 */
public class CrearLibro extends javax.swing.JFrame {
    private String archivoAutores = "autores.txt";
    private String archivoLibros = "libros.txt";
    private List<Autor> listaAutores;
    
    public CrearLibro() {
        initComponents();
        listaAutores = new ArrayList<>();
        leerAutores(archivoAutores);
    }
    
    private void leerAutores(String archivo) {
        try {
            BufferedReader reader = new BufferedReader(new FileReader(archivo));
            String linea;
            cboxAutores.removeAllItems();  // Limpiar ítems previos en el JComboBox

            while ((linea = reader.readLine()) != null) {
                // Dividimos la línea por el tabulador (\t)
                String[] datos = linea.split("\t");
                if (datos.length == 2) {
                    String codigo = datos[0];  // Código de autor
                    String nombre = datos[1];  // Nombre de autor

                    // Crear objeto Autor
                    Autor autor = new Autor(codigo, nombre);
                    
                    listaAutores.add(autor);
                    
                    // Añadir el objeto Autor al JComboBox
                    cboxAutores.addItem(autor.getNombre());  // Se añadirá el nombre porque toString() en Autor devuelve el nombre
                }
            }

            reader.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo de autores: " + e.getMessage());
        }
    }
    private String getCodigoAutorSeleccionado() {
        String nombreSeleccionado = (String) cboxAutores.getSelectedItem();
        for (Autor autor : listaAutores) {
            if (autor.getNombre().equals(nombreSeleccionado)) {
                return autor.getCodigo();  // Retornar el código del autor
            }
        }
        return "No se encontro el codigo";  // En caso de no encontrar el autor
    }
    
    private void guardarLibro(){
        String isbn = txtISBN.getText();
        String titulo = txtTitulo.getText();
        String sinopsis = txaSinopsis.getText();
        Autor autorSeleccionado = null;
        for (Autor autor : listaAutores) {
            if (autor.getCodigo().equals(getCodigoAutorSeleccionado())) {
                autorSeleccionado = autor;
                break;
            }
        }
        String genero = "";
        if (rdbtnTerror.isSelected()) {
            genero = "Terror";
        } else if (rdbtnRomance.isSelected()) {
            genero = "Romance";
        } else if (rdbtnCienciaFiccion.isSelected()) {
            genero = "Ciencia Ficción";
        } else if (rdbtnFantasia.isSelected()) {
            genero = "Fantasía";
        }
        boolean leido = chboxLeido.isSelected();
        boolean loTengo = chboxLoTengo.isSelected();
        Libro libro = new Libro(isbn, titulo, autorSeleccionado, sinopsis, genero, leido, loTengo);
        
        try{
            BufferedWriter writer = new BufferedWriter(new FileWriter(archivoLibros,true));
            
            writer.write(libro.getIsbn() + "\t" +
                     libro.getTitulo() + "\t" +
                     libro.getAutor().getCodigo() + "\t" +  // Guardamos el código del autor
                     libro.getSinopsis() + "\t" +
                     libro.getGenero() + "\t" +
                     libro.isLeido() + "\t" +
                     libro.isLoTengo());
            writer.newLine();
            writer.close();
            limpiar();
        } catch(IOException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void limpiar(){
        txtISBN.setText("");
        txtTitulo.setText("");
        cboxAutores.setSelectedIndex(0);
        txaSinopsis.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        cboxAutores = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnNuevoAutor = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSinopsis = new javax.swing.JTextArea();
        rdbtnCienciaFiccion = new javax.swing.JRadioButton();
        rdbtnTerror = new javax.swing.JRadioButton();
        rdbtnFantasia = new javax.swing.JRadioButton();
        rdbtnRomance = new javax.swing.JRadioButton();
        chboxLeido = new javax.swing.JCheckBox();
        chboxLoTengo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Libro");

        jLabel1.setText("ISBN:");

        jLabel2.setText("Título:");

        jLabel3.setText("Autor:");

        jLabel4.setText("Sinopsis:");

        jLabel5.setText("Género:");

        txtISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtISBNKeyTyped(evt);
            }
        });

        cboxAutores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevoAutor.setText("Nuevo autor");
        btnNuevoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAutorActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txaSinopsis.setColumns(20);
        txaSinopsis.setRows(5);
        jScrollPane1.setViewportView(txaSinopsis);

        g1.add(rdbtnCienciaFiccion);
        rdbtnCienciaFiccion.setText("Ciencia Ficcion");

        g1.add(rdbtnTerror);
        rdbtnTerror.setSelected(true);
        rdbtnTerror.setText("Terror");

        g1.add(rdbtnFantasia);
        rdbtnFantasia.setText("Fantasia");

        g1.add(rdbtnRomance);
        rdbtnRomance.setText("Romance");

        chboxLeido.setText("Leido");

        chboxLoTengo.setText("Lo tengo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(btnCancelar))
                            .addComponent(btnNuevoAutor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxAutores, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtISBN, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chboxLeido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chboxLoTengo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbtnTerror)
                                    .addComponent(rdbtnRomance))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbtnFantasia)
                                    .addComponent(rdbtnCienciaFiccion))))
                        .addGap(109, 109, 109)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboxAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevoAutor)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnCienciaFiccion)
                            .addComponent(rdbtnTerror))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnFantasia)
                            .addComponent(rdbtnRomance))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chboxLeido)
                            .addComponent(chboxLoTengo))))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String isbn = txtISBN.getText();
        String titulo = txtTitulo.getText();
        
        if (isbn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El ISBN es obligatorio.", "Error", JOptionPane.ERROR_MESSAGE);
            txtISBN.requestFocus();
            return;
        }
        if (titulo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El título es obligatorio.", "Error", JOptionPane.ERROR_MESSAGE);
            txtTitulo.requestFocus();
            return;
        }
        
        guardarLibro();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAutorActionPerformed
        // TODO add your handling code here:
        NuevoAutor frame = new NuevoAutor();
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Cuando se cierre, recargar la lista de autores
                leerAutores(archivoAutores);  
            }
        });
        frame.setVisible(true);
    }//GEN-LAST:event_btnNuevoAutorActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtISBNKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtISBNKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoAutor;
    private javax.swing.JComboBox<String> cboxAutores;
    private javax.swing.JCheckBox chboxLeido;
    private javax.swing.JCheckBox chboxLoTengo;
    private javax.swing.ButtonGroup g1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbtnCienciaFiccion;
    private javax.swing.JRadioButton rdbtnFantasia;
    private javax.swing.JRadioButton rdbtnRomance;
    private javax.swing.JRadioButton rdbtnTerror;
    private javax.swing.JTextArea txaSinopsis;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
